---
title: "Introduction to acronyms"
description: >
  Learn how to get started with the basics of the **acronyms** extension.
---

The goal of **acronyms** is to provide support for acronyms to Quarto
documents, in a similar way to what
[glossaries](https://www.ctan.org/pkg/glossaries) achieve for LaTeX.

Basically, it allows you to define a list of acronyms, and to automatically
replace acronyms inside the document.
A list of all defined acronyms along with their definitions is also generated
and inserted.

Using **acronyms** can be done in 3 simple steps:

1. Installing the extension
2. Defining acronyms
3. Using acronyms


## Installing the extension

This extension can be installed through the standard Quarto `add` command:

```sh
quarto add rchaput/acronyms
```

This command will download the latest version and install it locally to your
`_extensions` folder. Please see the official
[Quarto documentation](https://quarto.org/docs/extensions/managing.html)
for details.

You can also install a specific version by specifying the version tag at the
end of the command, for example:

```sh
quarto add rchaput/acronyms@v2.0.1
```

where `v2.0.1` is the desired version. The list of available tags can be
seen in the list of [releases](https://github.com/rchaput/acronyms/releases).

Make sure that your Quarto document(s) contain the following lines in the
YAML metadata, to load the *acronyms* extension:

```yaml
---
filters:
  - acronyms
---
```


## Defining acronyms

Prior to using acronyms in the Quarto document, they must be defined in
the YAML metadata.

An acronym is defined as:

- a *key*, which is used to refer to the acronym throughout the document;
- a *short name*, which is usually the acronym itself;
- a *long name*, which is usually what the acronym stands for.

To make the list less verbose, if the key is not provided, **acronyms**
uses the short name as a default key for the acronym.

The following example defines 2 acronyms:

```yaml
---
acronyms:
  keys:
    - shortname: qmd
      longname: Quarto document
    - key: yaml
      shortname: YAML
      longname: YAML Ain't Markup Language
---
```


## Using acronyms

Finally, to insert an acronym into the document, simply use `\acr{<KEY>}`,
where `<KEY>` is an acronym's key, as defined in the YAML metadata.

This command will be automatically replaced by **acronyms**. The result
depends on the chosen style (see [styles](articles/styles.qmd) for more 
details). Most styles will also make a difference between the first use, and 
the next occurrences.

By default, **acronyms** will replace as follows:

- first use: `<long name> (<short name>)`
- next uses: `<short name>`

The next lines show an example of how **acronyms** replaces acronyms
in a document, assuming the acronyms `qmd` and `yaml` have been defined, as
per the previous example.

```md
\acrs{qmd} allow to easily write technical content. A \acr{qmd} uses \acr{yaml}
for the metadata.
```

> Quarto documents (qmds) allow to easily write technical content. A qmd uses
> YAML Ain't Markup Language (YAML) for the metadata.

Notice how by using `\acrs` we can pluralize the acronym; you can read more
about that in [Plural form](articles/plural.qmd).


## Using markdown in acronyms

You can use basic markdown formatting in the `longname` and `shortname`
fields of your acronym definitions. For example, you can add **bold**,
*italic*, ~subscript~, and ^superscript^.

There are a few things to keep in mind when using markdown in acronyms.
It is generally best two wrap short and long names in quotes, otherwise
issues with yaml parsing will be encountered. Also, a `key` must be
provided if markdown is used in the short name (this is not required
if markdown is limited to long name). Finally, a plural form must be
explicitly provided when using markdown. An example of a yaml that
uses markdown follows:

```yaml
---
acronyms:
  keys:
    - shortname: CDI
      longname: "*Clostridium difficile* infection
      plural:
        shortname: CDIs
        longname: "*Clostridium difficile* infections"
    - key: ecoli
      shortname: "*E. coli*"
      longname: "*Escherichia coli*"
---
```

## Complete example

A complete example showing the previous instructions as a single file can
be found [here](https://github.com/rchaput/acronyms/blob/main/example.qmd).


## Next steps

The current vignette gives you the tools for a simple document, using the
(sane) defaults provided by **acronyms**.
However, most of the mechanisms are highly configurable and offer various
options.

Available options are described in [Options](articles/options.qmd), and several
tutorials for advanced usages are listed in [Advanced usage](advanced/index.qmd).

You can also read more about the new [shortcode](articles/shortcodes.qmd)
syntax.

[Styles](articles/styles.qmd) lists the different styles that can be used,
along with a small example to visualize each of them.
