name: automatic-testing

on:
  push:
    # Run on all branches, except gh-pages (as it is only for documentation)
    branches-ignore: [gh-pages]
  workflow_dispatch:
    # Allow to run manually

jobs:
  testing:
    strategy:
      # We want to try all combinations, even if one fails
      fail-fast: false
      # Run the release version of quarto for all OS
      matrix:
        quarto_version: [release]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Additionally, we want to run the `pre-release` version for Ubuntu
        include:
          - os: ubuntu-latest
            quarto_version: pre-release
    runs-on: ${{ matrix.os }}
    # At some point, we will probably want to setup a strategy matrix here
    # (perhaps, to test with both quarto's latest release and pre-release)
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ matrix.quarto_version }}

      - name: Run tests
        run: quarto run tests/run_tests.ts
